ports:
  - port: 5000
  - port: 3000

tasks:
  - before: |
      export FLASK_APP=backend:app
      export FLASK_ENV=development
    init: |
      pip install -e backend
      flask init-db
    command: |
      flask run
  - init: |
      cd saffron_motion && npm install
    command: |
      npm start

vscode:
  extensions:
    - ms-python.python
